name: Upload Go test results

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Get Maelstrom
        run: make setup-maelstrom
      - name: Install dependencies
        run: sudo apt-get install -y gnuplot openjdk-17-jdk graphviz
      # Tests of the challenge
      - name: Run Unique ID Test
        run: make unique-id
      - name: Run Broadcast Test
        run: make broadcast-test

